<a href="https://colab.research.google.com/github/mikeytw11/Hockey/blob/main/Descriptive_vs_Predictive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


The goal of this script is to compare the GF%, CF% and xGF% from the first 41 games of the season to the last 41 games of the season. This data views only full seasonsa and so the 12/13, 19/20 and 20/21 seasons are excluded. Other than that we are looking at full seasons from 07/08 to 21/22.

In [59]:
#Import dependencies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
#Import data for each team during the 2022-2023 season.
df_col = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_col_on-ice_all_regular_2023-06-20.csv")
df_chi = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_chi_on-ice_all_regular_2023-06-20.csv")
df_cbj = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_cbj_on-ice_all_regular_2023-06-20.csv")
df_stl = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_stl_on-ice_all_regular_2023-06-20.csv")
df_bos = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_bos_on-ice_all_regular_2023-06-20.csv")
df_mtl = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_mtl_on-ice_all_regular_2023-06-20.csv")
df_van = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_van_on-ice_all_regular_2023-06-20.csv")
df_wsh = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_wsh_on-ice_all_regular_2023-06-20.csv")
df_ari = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_ari_on-ice_all_regular_2023-06-20.csv")
df_nj = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_n.j_on-ice_all_regular_2023-06-19.csv")
df_ana = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_ana_on-ice_all_regular_2023-06-20.csv")
df_cgy = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_cgy_on-ice_all_regular_2023-06-20.csv")
df_phi = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_phi_on-ice_all_regular_2023-06-20.csv")
df_car = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_car_on-ice_all_regular_2023-06-20.csv")
df_nyi = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_nyi_on-ice_all_regular_2023-06-20.csv")
df_wpg = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_wpg_on-ice_all_regular_2023-06-20.csv")
df_la = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_l.a_on-ice_all_regular_2023-06-20.csv")
df_vgk = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_vgk_on-ice_all_regular_2023-06-20.csv")
df_tor = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_tor_on-ice_all_regular_2023-06-20.csv")
df_tb = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_t.b_on-ice_all_regular_2023-06-20.csv")
df_edm = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_edm_on-ice_all_regular_2023-06-20.csv")
df_fla = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_fla_on-ice_all_regular_2023-06-20.csv")
df_pit = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_pit_on-ice_all_regular_2023-06-20.csv")
df_nsh = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_nsh_on-ice_all_regular_2023-06-20.csv")
df_nyr = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_nyr_on-ice_all_regular_2023-06-20.csv")
df_det = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_det_on-ice_all_regular_2023-06-20.csv")
df_buf = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_buf_on-ice_all_regular_2023-06-20.csv")
df_ott = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_ott_on-ice_all_regular_2023-06-20.csv")
df_sj = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_s.j_on-ice_all_regular_2023-06-20.csv")
df_dal = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_dal_on-ice_all_regular_2023-06-20.csv")
df_min = pd.read_csv("https://raw.githubusercontent.com/mikeytw11/Hockey/main/2022-2023/EH_game_log_min_on-ice_all_regular_2023-06-20.csv")

In [61]:
#Drop last row of "total" data.
df_col = df_col.loc[:81]
df_chi = df_chi.loc[:81]
df_cbj = df_cbj.loc[:81]
df_stl = df_stl.loc[:81]
df_bos = df_bos.loc[:81]
df_mtl = df_mtl.loc[:81]
df_van = df_van.loc[:81]
df_wsh = df_wsh.loc[:81]
df_ari = df_ari.loc[:81]
df_nj = df_nj.loc[:81]
df_ana = df_ana.loc[:81]
df_cgy = df_cgy.loc[:81]
df_phi = df_phi.loc[:81]
df_car = df_car.loc[:81]
df_nyi = df_nyi.loc[:81]
df_wpg = df_wpg.loc[:81]
df_la = df_la.loc[:81]
df_vgk = df_vgk.loc[:81]
df_tor = df_tor.loc[:81]
df_tb = df_tb.loc[:81]
df_edm = df_edm.loc[:81]
df_fla = df_fla.loc[:81]
df_pit = df_pit.loc[:81]
df_nsh = df_nsh.loc[:81]
df_nyr = df_nyr.loc[:81]
df_det = df_det.loc[:81]
df_buf = df_buf.loc[:81]
df_ott = df_ott.loc[:81]
df_sj = df_sj.loc[:81]
df_dal = df_dal.loc[:81]
df_min = df_min.loc[:81]

In [62]:
#Restrict Data to Team, Game_ID, GF, GA, CF, CA, xGF, xGA
df_col = df_col.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_chi = df_chi.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_cbj = df_cbj.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_stl = df_stl.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_bos = df_bos.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_mtl = df_mtl.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_van = df_van.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_wsh = df_wsh.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_ari = df_ari.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_nj = df_nj.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_ana = df_ana.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_cgy = df_cgy.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_phi = df_phi.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_car = df_car.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_nyi = df_nyi.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_wpg = df_wpg.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_la = df_la.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_vgk = df_vgk.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_tor = df_tor.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_tb = df_tb.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_edm = df_edm.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_fla = df_fla.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_pit = df_pit.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_nsh = df_nsh.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_nyr = df_nyr.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_det = df_det.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_buf = df_buf.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_ott = df_ott.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_sj = df_sj.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_dal = df_dal.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]
df_min = df_min.loc[:,['Team', 'GF', 'GA', 'CF', 'CA', 'xGF', 'xGA']]

In [63]:
#Separate first 41 games fromt he dataframe.
df_col_1 = df_col.loc[:40]
df_chi_1 = df_chi.loc[:40]
df_cbj_1 = df_cbj.loc[:40]
df_stl_1 = df_stl.loc[:40]
df_bos_1 = df_bos.loc[:40]
df_mtl_1 = df_mtl.loc[:40]
df_van_1 = df_van.loc[:40]
df_wsh_1 = df_wsh.loc[:40]
df_ari_1 = df_ari.loc[:40]
df_nj_1 = df_nj.loc[:40]
df_ana_1 = df_ana.loc[:40]
df_cgy_1 = df_cgy.loc[:40]
df_phi_1 = df_phi.loc[:40]
df_car_1 = df_car.loc[:40]
df_nyi_1 = df_nyi.loc[:40]
df_wpg_1 = df_wpg.loc[:40]
df_la_1 = df_la.loc[:40]
df_vgk_1 = df_vgk.loc[:40]
df_tor_1 = df_tor.loc[:40]
df_tb_1 = df_tb.loc[:40]
df_edm_1 = df_edm.loc[:40]
df_fla_1 = df_fla.loc[:40]
df_pit_1 = df_pit.loc[:40]
df_nsh_1 = df_nsh.loc[:40]
df_nyr_1 = df_nyr.loc[:40]
df_det_1 = df_det.loc[:40]
df_buf_1 = df_buf.loc[:40]
df_ott_1 = df_ott.loc[:40]
df_sj_1 = df_sj.loc[:40]
df_dal_1 = df_dal.loc[:40]
df_min_1 = df_min.loc[:40]

In [64]:
#Separate last 41 games from data.
df_col_2 = df_col.loc[41:81]
df_chi_2 = df_chi.loc[41:81]
df_cbj_2 = df_cbj.loc[41:81]
df_stl_2 = df_stl.loc[41:81]
df_bos_2 = df_bos.loc[41:81]
df_mtl_2 = df_mtl.loc[41:81]
df_van_2 = df_van.loc[41:81]
df_wsh_2 = df_wsh.loc[41:81]
df_ari_2 = df_ari.loc[41:81]
df_nj_2 = df_nj.loc[41:81]
df_ana_2 = df_ana.loc[41:81]
df_cgy_2 = df_cgy.loc[41:81]
df_phi_2 = df_phi.loc[41:81]
df_car_2 = df_car.loc[41:81]
df_nyi_2 = df_nyi.loc[41:81]
df_wpg_2 = df_wpg.loc[41:81]
df_la_2 = df_la.loc[41:81]
df_vgk_2 = df_vgk.loc[41:81]
df_tor_2 = df_tor.loc[41:81]
df_tb_2 = df_tb.loc[41:81]
df_edm_2 = df_edm.loc[41:81]
df_fla_2 = df_fla.loc[41:81]
df_pit_2 = df_pit.loc[41:81]
df_nsh_2 = df_nsh.loc[41:81]
df_nyr_2 = df_nyr.loc[41:81]
df_det_2 = df_det.loc[41:81]
df_buf_2 = df_buf.loc[41:81]
df_ott_2 = df_ott.loc[41:81]
df_sj_2 = df_sj.loc[41:81]
df_dal_2 = df_dal.loc[41:81]
df_min_2 = df_min.loc[41:81]

In [66]:
#Create new dataframe for Minnesota.
pd.options.mode.chained_assignment = None
df_min_1['GF%_41'] = ((df_min_1['GF'].sum()/(df_min_1['GF'].sum() + df_min_1['GA'].sum()))*100).round(2)
df_min_1['CF%_41'] = ((df_min_1['CF'].sum()/(df_min_1['CF'].sum() + df_min_1['CA'].sum()))*100).round(2)
df_min_1['xGF%_41'] = ((df_min_1['xGF'].sum()/(df_min_1['xGF'].sum() + df_min_1['xGA'].sum()))*100).round(2)
df_min_1 = df_min_1.loc[:0]
df_min_1 = df_min_1.drop(columns = ['GF','GA', 'CF', 'CA', 'xGF', 'xGA'])
df_min_2['GF%_82'] = ((df_min_2['GF'].sum()/(df_min_2['GF'].sum() + df_min_2['GA'].sum()))*100).round(2)
df_min_2['CF%_82'] = ((df_min_2['CF'].sum()/(df_min_2['CF'].sum() + df_min_2['CA'].sum()))*100).round(2)
df_min_2['xGF%_82'] = ((df_min_2['xGF'].sum()/(df_min_2['xGF'].sum() + df_min_2['xGA'].sum()))*100).round(2)
df_min_2 = df_min_2.loc[:41]
df_min_2 = df_min_2.drop(columns = ['GF','GA', 'CF', 'CA', 'xGF', 'xGA'])

#Merge both halves of the season into one.
df_min = pd.merge(df_min_1, df_min_2, how="outer", on=['Team'])
df_min

  Team  GF%_41  CF%_41  xGF%_41  GF%_82  CF%_82  xGF%_82
0  MIN   52.56   51.26    53.01   51.87   49.32    51.99

In [67]:
#Create new dataframe for New Jersey Devils.
df_nj_1['GF%_41'] = ((df_nj_1['GF'].sum()/(df_nj_1['GF'].sum() + df_nj_1['GA'].sum()))*100).round(2)
df_nj_1['CF%_41'] = ((df_nj_1['CF'].sum()/(df_nj_1['CF'].sum() + df_nj_1['CA'].sum()))*100).round(2)
df_nj_1['xGF%_41'] = ((df_nj_1['xGF'].sum()/(df_nj_1['xGF'].sum() + df_nj_1['xGA'].sum()))*100).round(2)
df_nj_1 = df_nj_1.loc[:0]
df_nj_1 = df_nj_1.drop(columns = ['GF','GA', 'CF', 'CA', 'xGF', 'xGA'])
df_nj_2['GF%_82'] = ((df_nj_2['GF'].sum()/(df_nj_2['GF'].sum() + df_nj_2['GA'].sum()))*100).round(2)
df_nj_2['CF%_82'] = ((df_nj_2['CF'].sum()/(df_nj_2['CF'].sum() + df_nj_2['CA'].sum()))*100).round(2)
df_nj_2['xGF%_82'] = ((df_nj_2['xGF'].sum()/(df_nj_2['xGF'].sum() + df_nj_2['xGA'].sum()))*100).round(2)
df_nj_2 = df_nj_2.loc[:41]
df_nj_2 = df_nj_2.drop(columns = ['GF','GA', 'CF', 'CA', 'xGF', 'xGA'])

#Merge both halves of the season into one.
df_nj = pd.merge(df_nj_1, df_nj_2, how="outer", on=['Team'])
df_nj

  Team  GF%_41  CF%_41  xGF%_41  GF%_82  CF%_82  xGF%_82
0  N.J   56.33   54.85    56.58   57.01   53.53     55.8

In [68]:
#Merge data into one dataframe.
df = pd.concat([df_nj, df_min], axis=0)
df

  Team  GF%_41  CF%_41  xGF%_41  GF%_82  CF%_82  xGF%_82
0  N.J   56.33   54.85    56.58   57.01   53.53    55.80
0  MIN   52.56   51.26    53.01   51.87   49.32    51.99

In [20]:
#Create row for GF%, CF% and xGF%
nj_41 = [{'Name':'Devils', 'GF%_41':((df_nj_1['GF'].sum()/(df_nj_1['GF'].sum() + df_nj_1['GA'].sum()))*100).round(2), 'CF%_41':((df_nj_1['CF'].sum()/(df_nj_1['CF'].sum() + df_nj_1['CA'].sum()))*100).round(2),
 'xGF%_41':((df_nj_1['xGF'].sum()/(df_nj_1['xGF'].sum() + df_nj_1['xGA'].sum()))*100).round(2)}]
col_41 = [{'Name':'Avalanche', 'GF%_41':((df_nj_1['GF'].sum()/(df_col_1['GF'].sum() + df_col_1['GA'].sum()))*100).round(2), 'CF%_41':((df_col_1['CF'].sum()/(df_col_1['CF'].sum() + df_col_1['CA'].sum()))*100).round(2),
 'xGF%_41':((df_col_1['xGF'].sum()/(df_col_1['xGF'].sum() + df_col_1['xGA'].sum()))*100).round(2)}]
nj_82 = [{'Name':'Devils', 'GF%_82':((df_nj_2['GF'].sum()/(df_nj_2['GF'].sum() + df_nj_2['GA'].sum()))*100).round(2), 'CF%_82':((df_nj_2['CF'].sum()/(df_nj_2['CF'].sum() + df_nj_2['CA'].sum()))*100).round(2),
 'xGF%_82':((df_nj_2['xGF'].sum()/(df_nj_2['xGF'].sum() + df_nj_2['xGA'].sum()))*100).round(2)}]
col_82 = [{'Name':'Avalanche', 'GF%_82':((df_col_2['GF'].sum()/(df_col_2['GF'].sum() + df_col_2['GA'].sum()))*100).round(2), 'CF%_82':((df_col_2['CF'].sum()/(df_col_2['CF'].sum() + df_col_2['CA'].sum()))*100).round(2),
 'xGF%_82':((df_col_2['xGF'].sum()/(df_col_2['xGF'].sum() + df_col_2['xGA'].sum()))*100).round(2)}]
df_41=pd.DataFrame(nj_41:col_41)
df_82=pd.DataFrame(nj_82:col_82)
df = pd.merge(df_41, df_82, how="outer", on=['Name'])
df

SyntaxError: ignored